### ISSUE TITLE
Polluting site-packages with tests

### ISSUE THREAD

**Issue by karolyi** [Adyen/adyen-python-api-library#334]
Hello,

your package pollutes the site-packages directory with tests, upon installing. I was shocked to notice. See below. I've made a test venv for it.

### Before installing adyen:
```
$ find venv/lib64/python3.12/site-packages/
venv/lib64/python3.12/site-packages/
```

### After installing adyen:
```
$ find venv/lib64/python3.12/site-packages/
venv/lib64/python3.12/site-packages/
venv/lib64/python3.12/site-packages/test
venv/lib64/python3.12/site-packages/test/CheckoutUtilityTest.py
venv/lib64/python3.12/site-packages/test/LegalEntityManagementTest.py
venv/lib64/python3.12/site-packages/test/ClientTest.py
venv/lib64/python3.12/site-packages/test/StoredValueTest.py
venv/lib64/python3.12/site-packages/test/PaymentTest.py
venv/lib64/python3.12/site-packages/test/RecurringTest.py
venv/lib64/python3.12/site-packages/test/DetermineEndpointTest.py
venv/lib64/python3.12/site-packages/test/DisputesTest.py
venv/lib64/python3.12/site-packages/test/__init__.py
venv/lib64/python3.12/site-packages/test/ThirdPartyPayoutTest.py
venv/lib64/python3.12/site-packages/test/ManagementTest.py
venv/lib64/python3.12/site-packages/test/TerminalTest.py
venv/lib64/python3.12/site-packages/test/BaseTest.py
venv/lib64/python3.12/site-packages/test/CheckoutTest.py
venv/lib64/python3.12/site-packages/test/UtilTest.py
venv/lib64/python3.12/site-packages/test/BinLookupTest.py
venv/lib64/python3.12/site-packages/test/ModificationTest.py
venv/lib64/python3.12/site-packages/test/__pycache__
venv/lib64/python3.12/site-packages/test/__pycache__/BinLookupTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/LegalEntityManagementTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/DataProtectionTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/DisputesTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/CheckoutTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/DetermineEndpointTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/ClientTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/BaseTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/ThirdPartyPayoutTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/ModificationTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/PaymentTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/ManagementTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/BalancePlatformTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/TransfersTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/TerminalTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/RecurringTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/StoredValueTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/UtilTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/CheckoutUtilityTest.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/test/BalancePlatformTest.py
venv/lib64/python3.12/site-packages/test/DataProtectionTest.py
venv/lib64/python3.12/site-packages/test/TransfersTest.py
venv/lib64/python3.12/site-packages/Adyen-12.3.0.dist-info
venv/lib64/python3.12/site-packages/Adyen-12.3.0.dist-info/INSTALLER
venv/lib64/python3.12/site-packages/Adyen-12.3.0.dist-info/top_level.txt
venv/lib64/python3.12/site-packages/Adyen-12.3.0.dist-info/REQUESTED
venv/lib64/python3.12/site-packages/Adyen-12.3.0.dist-info/LICENSE.md
venv/lib64/python3.12/site-packages/Adyen-12.3.0.dist-info/METADATA
venv/lib64/python3.12/site-packages/Adyen-12.3.0.dist-info/RECORD
venv/lib64/python3.12/site-packages/Adyen-12.3.0.dist-info/WHEEL
venv/lib64/python3.12/site-packages/Adyen
venv/lib64/python3.12/site-packages/Adyen/settings.py
venv/lib64/python3.12/site-packages/Adyen/__init__.py
venv/lib64/python3.12/site-packages/Adyen/client.py
venv/lib64/python3.12/site-packages/Adyen/exceptions.py
venv/lib64/python3.12/site-packages/Adyen/services
venv/lib64/python3.12/site-packages/Adyen/services/checkout
venv/lib64/python3.12/site-packages/Adyen/services/checkout/classic_checkout_sdk_api.py
venv/lib64/python3.12/site-packages/Adyen/services/checkout/orders_api.py
venv/lib64/python3.12/site-packages/Adyen/services/checkout/payment_links_api.py
venv/lib64/python3.12/site-packages/Adyen/services/checkout/utility_api.py
venv/lib64/python3.12/site-packages/Adyen/services/checkout/payments_api.py
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__init__.py
venv/lib64/python3.12/site-packages/Adyen/services/checkout/donations_api.py
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/payments_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/classic_checkout_sdk_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/recurring_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/donations_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/utility_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/modifications_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/payment_links_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/orders_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/checkout/recurring_api.py
venv/lib64/python3.12/site-packages/Adyen/services/checkout/modifications_api.py
venv/lib64/python3.12/site-packages/Adyen/services/disputes.py
venv/lib64/python3.12/site-packages/Adyen/services/storedValue.py
venv/lib64/python3.12/site-packages/Adyen/services/terminal.py
venv/lib64/python3.12/site-packages/Adyen/services/balanceControl.py
venv/lib64/python3.12/site-packages/Adyen/services/payments
venv/lib64/python3.12/site-packages/Adyen/services/payments/payments_api.py
venv/lib64/python3.12/site-packages/Adyen/services/payments/__init__.py
venv/lib64/python3.12/site-packages/Adyen/services/payments/__pycache__
venv/lib64/python3.12/site-packages/Adyen/services/payments/__pycache__/payments_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/payments/__pycache__/modifications_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/payments/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/payments/modifications_api.py
venv/lib64/python3.12/site-packages/Adyen/services/binlookup.py
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/documents_api.py
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/transfer_instruments_api.py
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/legal_entities_api.py
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/terms_of_service_api.py
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__init__.py
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/hosted_onboarding_api.py
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__/hosted_onboarding_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__/transfer_instruments_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__/pci_questionnaires_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__/legal_entities_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__/business_lines_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__/terms_of_service_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__/documents_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/pci_questionnaires_api.py
venv/lib64/python3.12/site-packages/Adyen/services/legalEntityManagement/business_lines_api.py
venv/lib64/python3.12/site-packages/Adyen/services/transfers
venv/lib64/python3.12/site-packages/Adyen/services/transfers/transfers_api.py
venv/lib64/python3.12/site-packages/Adyen/services/transfers/transactions_api.py
venv/lib64/python3.12/site-packages/Adyen/services/transfers/__init__.py
venv/lib64/python3.12/site-packages/Adyen/services/transfers/__pycache__
venv/lib64/python3.12/site-packages/Adyen/services/transfers/__pycache__/transfers_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/transfers/__pycache__/transactions_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/transfers/__pycache__/capital_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/transfers/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/transfers/capital_api.py
venv/lib64/python3.12/site-packages/Adyen/services/__init__.py
venv/lib64/python3.12/site-packages/Adyen/services/recurring.py
venv/lib64/python3.12/site-packages/Adyen/services/base.py
venv/lib64/python3.12/site-packages/Adyen/services/payouts
venv/lib64/python3.12/site-packages/Adyen/services/payouts/__init__.py
venv/lib64/python3.12/site-packages/Adyen/services/payouts/instant_payouts_api.py
venv/lib64/python3.12/site-packages/Adyen/services/payouts/__pycache__
venv/lib64/python3.12/site-packages/Adyen/services/payouts/__pycache__/initialization_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/payouts/__pycache__/reviewing_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/payouts/__pycache__/instant_payouts_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/payouts/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/payouts/reviewing_api.py
venv/lib64/python3.12/site-packages/Adyen/services/payouts/initialization_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/network_tokens_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/account_holders_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/manage_card_pin_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/payment_instrument_groups_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/manage_sca_devices_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__init__.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/balance_accounts_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/card_orders_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/grant_accounts_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/manage_card_pin_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/transaction_rules_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/account_holders_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/payment_instruments_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/bank_account_validation_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/grant_offers_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/network_tokens_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/transfer_routes_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/card_orders_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/manage_sca_devices_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/platform_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/grant_accounts_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/payment_instrument_groups_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/balance_accounts_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/grant_offers_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/platform_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/bank_account_validation_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/payment_instruments_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/transaction_rules_api.py
venv/lib64/python3.12/site-packages/Adyen/services/balancePlatform/transfer_routes_api.py
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/terminal.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/binlookup.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/storedValue.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/recurring.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/base.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/dataProtection.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/balanceControl.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/disputes.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management
venv/lib64/python3.12/site-packages/Adyen/services/management/users_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/allowed_origins_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminal_actions_terminal_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/users_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminal_orders_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/client_key_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/webhooks_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/account_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/account_store_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/api_credentials_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/split_configuration_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminal_orders_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/__init__.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminal_settings_terminal_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/payment_methods_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/webhooks_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/android_files_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/account_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/allowed_origins_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/client_key_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/payment_methods_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/api_credentials_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/split_configuration_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/account_store_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/users_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/api_credentials_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/account_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/users_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminal_settings_store_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/api_key_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/payout_settings_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminal_orders_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminal_settings_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/allowed_origins_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/webhooks_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/api_key_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminal_settings_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/account_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminal_settings_terminal_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/allowed_origins_merchant_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/my_api_credential_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminal_actions_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/client_key_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/android_files_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminal_actions_terminal_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminal_orders_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/terminals_terminal_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/webhooks_company_level_api.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/services/management/api_credentials_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/payout_settings_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/api_key_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/client_key_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminals_terminal_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminal_settings_store_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminal_settings_merchant_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminal_actions_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/api_key_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/my_api_credential_api.py
venv/lib64/python3.12/site-packages/Adyen/services/management/terminal_settings_company_level_api.py
venv/lib64/python3.12/site-packages/Adyen/services/dataProtection.py
venv/lib64/python3.12/site-packages/Adyen/__pycache__
venv/lib64/python3.12/site-packages/Adyen/__pycache__/exceptions.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/__pycache__/httpclient.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/__pycache__/util.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/__pycache__/settings.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/__pycache__/client.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/__pycache__/__init__.cpython-312.pyc
venv/lib64/python3.12/site-packages/Adyen/httpclient.py
venv/lib64/python3.12/site-packages/Adyen/util.py
```

**Comment by jillingk** [comment]
Hi @karolyi,

Thanks for reaching out here with this question! Which library version are you on currently?

Best, Jilling
Adyen

**Comment by karolyi** [comment]
Hey,

latest, of course.

**Comment by DjoykeAbyah** [comment]
Hi @karolyi,

I wanted to give you a quick update that we've merged the updated setup.py in our latest release!

Kind regards,

Djoyke
Adyen

**Comment by karolyi** [comment]
Thanks.

Did you stop releasing on pypi? The latest release on there is12.3.0 from May.

I can use github for releases, just let me know if that's the case.

**Comment by jillingk** [comment]
@karolyi,

Yes unfortunately we have not been able to release packages to pypi for a while as we're relying on the (very) understaffed pypi team to recover our account. Let us know if you're able to retrieve the package through Github, if not we will consider providing alternatives.

Best, Jilling
Adyen

**Comment by karolyi** [comment]
Hey,

did you actually test the installation? It still pollutes the site-packages, so not fixed.

I already use a whole lot of non-pypi sources (private and other decenralized sources) anyway so using this from github is not an issue, btw.

**Comment by jillingk** [comment]
Hi @karolyi,

Yes that's my bad, seemed like a trivial solution but apparently it did not quite work.

Should work with #345.

Best, Jilling
Adyen
